spring:
  datasource:
    master:
      url: jdbc:mysql://10.10.10.10:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      url: jdbc:mysql://10.10.10.10:3306/test2
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave2:
      url: jdbc:mysql://10.10.10.10:3306/test3
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none