spring:
  profiles:
    active: dev

swagger:
  title: Spring Boot 示例
  description: Spring Boot 示例Swagger
  serviceUrl: https://youngstream.tech
  version: 1.0
  contact:
    name: youngstream
    url: https://youngstream.tech
    email: ly1216045316@126.com
